/*
 * This file is generated by jOOQ.
 */
package edu.alma.teamleft;


import edu.alma.teamleft.tables.Address;
import edu.alma.teamleft.tables.AddressType;
import edu.alma.teamleft.tables.Client;
import edu.alma.teamleft.tables.County;
import edu.alma.teamleft.tables.Followups;
import edu.alma.teamleft.tables.PhoneNumber;
import edu.alma.teamleft.tables.PhoneNumberType;
import edu.alma.teamleft.tables.PreferredContact;
import edu.alma.teamleft.tables.Service;
import edu.alma.teamleft.tables.Staff;
import edu.alma.teamleft.tables.Status;
import edu.alma.teamleft.tables.Ticket;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.address_type</code>.
     */
    public static final AddressType ADDRESS_TYPE = AddressType.ADDRESS_TYPE;

    /**
     * The table <code>public.client</code>.
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>public.county</code>.
     */
    public static final County COUNTY = County.COUNTY;

    /**
     * The table <code>public.followups</code>.
     */
    public static final Followups FOLLOWUPS = Followups.FOLLOWUPS;

    /**
     * The table <code>public.phone_number</code>.
     */
    public static final PhoneNumber PHONE_NUMBER = PhoneNumber.PHONE_NUMBER;

    /**
     * The table <code>public.phone_number_type</code>.
     */
    public static final PhoneNumberType PHONE_NUMBER_TYPE = PhoneNumberType.PHONE_NUMBER_TYPE;

    /**
     * The table <code>public.preferred_contact</code>.
     */
    public static final PreferredContact PREFERRED_CONTACT = PreferredContact.PREFERRED_CONTACT;

    /**
     * The table <code>public.service</code>.
     */
    public static final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>public.staff</code>.
     */
    public static final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>public.status</code>.
     */
    public static final Status STATUS = Status.STATUS;

    /**
     * The table <code>public.ticket</code>.
     */
    public static final Ticket TICKET = Ticket.TICKET;
}
