/*
 * This file is generated by jOOQ.
 */
package edu.alma.teamleft.tables;


import edu.alma.teamleft.Keys;
import edu.alma.teamleft.Public;
import edu.alma.teamleft.tables.records.CountyRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class County extends TableImpl<CountyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.county</code>
     */
    public static final County COUNTY = new County();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CountyRecord> getRecordType() {
        return CountyRecord.class;
    }

    /**
     * The column <code>public.county.county_id</code>.
     */
    public final TableField<CountyRecord, Integer> COUNTY_ID = createField(DSL.name("county_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.county.county_name</code>.
     */
    public final TableField<CountyRecord, String> COUNTY_NAME = createField(DSL.name("county_name"), SQLDataType.VARCHAR(25), this, "");

    private County(Name alias, Table<CountyRecord> aliased) {
        this(alias, aliased, null);
    }

    private County(Name alias, Table<CountyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.county</code> table reference
     */
    public County(String alias) {
        this(DSL.name(alias), COUNTY);
    }

    /**
     * Create an aliased <code>public.county</code> table reference
     */
    public County(Name alias) {
        this(alias, COUNTY);
    }

    /**
     * Create a <code>public.county</code> table reference
     */
    public County() {
        this(DSL.name("county"), null);
    }

    public <O extends Record> County(Table<O> child, ForeignKey<O, CountyRecord> key) {
        super(child, key, COUNTY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CountyRecord, Integer> getIdentity() {
        return (Identity<CountyRecord, Integer>) super.getIdentity();
    }

    @Override
    public List<UniqueKey<CountyRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.COUNTY_ID_KEY);
    }

    @Override
    public County as(String alias) {
        return new County(DSL.name(alias), this);
    }

    @Override
    public County as(Name alias) {
        return new County(alias, this);
    }

    @Override
    public County as(Table<?> alias) {
        return new County(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public County rename(String name) {
        return new County(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public County rename(Name name) {
        return new County(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public County rename(Table<?> name) {
        return new County(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
