/*
 * This file is generated by jOOQ.
 */
package edu.alma.teamleft.tables;


import edu.alma.teamleft.Keys;
import edu.alma.teamleft.Public;
import edu.alma.teamleft.tables.records.PreferredContactRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PreferredContact extends TableImpl<PreferredContactRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.preferred_contact</code>
     */
    public static final PreferredContact PREFERRED_CONTACT = new PreferredContact();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PreferredContactRecord> getRecordType() {
        return PreferredContactRecord.class;
    }

    /**
     * The column <code>public.preferred_contact.preferred_contact_id</code>.
     */
    public final TableField<PreferredContactRecord, Integer> PREFERRED_CONTACT_ID = createField(DSL.name("preferred_contact_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.preferred_contact.contact_method</code>.
     */
    public final TableField<PreferredContactRecord, String> CONTACT_METHOD = createField(DSL.name("contact_method"), SQLDataType.VARCHAR(25), this, "");

    private PreferredContact(Name alias, Table<PreferredContactRecord> aliased) {
        this(alias, aliased, null);
    }

    private PreferredContact(Name alias, Table<PreferredContactRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.preferred_contact</code> table reference
     */
    public PreferredContact(String alias) {
        this(DSL.name(alias), PREFERRED_CONTACT);
    }

    /**
     * Create an aliased <code>public.preferred_contact</code> table reference
     */
    public PreferredContact(Name alias) {
        this(alias, PREFERRED_CONTACT);
    }

    /**
     * Create a <code>public.preferred_contact</code> table reference
     */
    public PreferredContact() {
        this(DSL.name("preferred_contact"), null);
    }

    public <O extends Record> PreferredContact(Table<O> child, ForeignKey<O, PreferredContactRecord> key) {
        super(child, key, PREFERRED_CONTACT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PreferredContactRecord, Integer> getIdentity() {
        return (Identity<PreferredContactRecord, Integer>) super.getIdentity();
    }

    @Override
    public List<UniqueKey<PreferredContactRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PREFERRED_CONTACT_ID_KEY);
    }

    @Override
    public PreferredContact as(String alias) {
        return new PreferredContact(DSL.name(alias), this);
    }

    @Override
    public PreferredContact as(Name alias) {
        return new PreferredContact(alias, this);
    }

    @Override
    public PreferredContact as(Table<?> alias) {
        return new PreferredContact(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PreferredContact rename(String name) {
        return new PreferredContact(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PreferredContact rename(Name name) {
        return new PreferredContact(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PreferredContact rename(Table<?> name) {
        return new PreferredContact(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
