/*
 * This file is generated by jOOQ.
 */
package edu.alma.teamleft.tables;


import edu.alma.teamleft.Keys;
import edu.alma.teamleft.Public;
import edu.alma.teamleft.tables.records.ServiceRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Service extends TableImpl<ServiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.service</code>
     */
    public static final Service SERVICE = new Service();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiceRecord> getRecordType() {
        return ServiceRecord.class;
    }

    /**
     * The column <code>public.service.service_id</code>.
     */
    public final TableField<ServiceRecord, Integer> SERVICE_ID = createField(DSL.name("service_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.service.service_name</code>.
     */
    public final TableField<ServiceRecord, String> SERVICE_NAME = createField(DSL.name("service_name"), SQLDataType.VARCHAR(25).nullable(false), this, "");

    private Service(Name alias, Table<ServiceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Service(Name alias, Table<ServiceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.service</code> table reference
     */
    public Service(String alias) {
        this(DSL.name(alias), SERVICE);
    }

    /**
     * Create an aliased <code>public.service</code> table reference
     */
    public Service(Name alias) {
        this(alias, SERVICE);
    }

    /**
     * Create a <code>public.service</code> table reference
     */
    public Service() {
        this(DSL.name("service"), null);
    }

    public <O extends Record> Service(Table<O> child, ForeignKey<O, ServiceRecord> key) {
        super(child, key, SERVICE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ServiceRecord, Integer> getIdentity() {
        return (Identity<ServiceRecord, Integer>) super.getIdentity();
    }

    @Override
    public List<UniqueKey<ServiceRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SERVICES_SERVICE_ID_KEY, Keys.SERVICES_SERVICE_NAME_KEY);
    }

    @Override
    public Service as(String alias) {
        return new Service(DSL.name(alias), this);
    }

    @Override
    public Service as(Name alias) {
        return new Service(alias, this);
    }

    @Override
    public Service as(Table<?> alias) {
        return new Service(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Service rename(String name) {
        return new Service(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Service rename(Name name) {
        return new Service(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Service rename(Table<?> name) {
        return new Service(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
