/*
 * This file is generated by jOOQ.
 */
package edu.alma.teamleft.tables.records;


import edu.alma.teamleft.tables.Followups;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FollowupsRecord extends TableRecordImpl<FollowupsRecord> implements Record4<Integer, Integer, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.followups.followup_id</code>.
     */
    public void setFollowupId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.followups.followup_id</code>.
     */
    public Integer getFollowupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.followups.ticket_id</code>.
     */
    public void setTicketId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.followups.ticket_id</code>.
     */
    public Integer getTicketId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.followups.followup_date</code>.
     */
    public void setFollowupDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.followups.followup_date</code>.
     */
    public LocalDateTime getFollowupDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.followups.followup_outcome</code>.
     */
    public void setFollowupOutcome(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.followups.followup_outcome</code>.
     */
    public String getFollowupOutcome() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, LocalDateTime, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, LocalDateTime, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Followups.FOLLOWUPS.FOLLOWUP_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Followups.FOLLOWUPS.TICKET_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Followups.FOLLOWUPS.FOLLOWUP_DATE;
    }

    @Override
    public Field<String> field4() {
        return Followups.FOLLOWUPS.FOLLOWUP_OUTCOME;
    }

    @Override
    public Integer component1() {
        return getFollowupId();
    }

    @Override
    public Integer component2() {
        return getTicketId();
    }

    @Override
    public LocalDateTime component3() {
        return getFollowupDate();
    }

    @Override
    public String component4() {
        return getFollowupOutcome();
    }

    @Override
    public Integer value1() {
        return getFollowupId();
    }

    @Override
    public Integer value2() {
        return getTicketId();
    }

    @Override
    public LocalDateTime value3() {
        return getFollowupDate();
    }

    @Override
    public String value4() {
        return getFollowupOutcome();
    }

    @Override
    public FollowupsRecord value1(Integer value) {
        setFollowupId(value);
        return this;
    }

    @Override
    public FollowupsRecord value2(Integer value) {
        setTicketId(value);
        return this;
    }

    @Override
    public FollowupsRecord value3(LocalDateTime value) {
        setFollowupDate(value);
        return this;
    }

    @Override
    public FollowupsRecord value4(String value) {
        setFollowupOutcome(value);
        return this;
    }

    @Override
    public FollowupsRecord values(Integer value1, Integer value2, LocalDateTime value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FollowupsRecord
     */
    public FollowupsRecord() {
        super(Followups.FOLLOWUPS);
    }

    /**
     * Create a detached, initialised FollowupsRecord
     */
    public FollowupsRecord(Integer followupId, Integer ticketId, LocalDateTime followupDate, String followupOutcome) {
        super(Followups.FOLLOWUPS);

        setFollowupId(followupId);
        setTicketId(ticketId);
        setFollowupDate(followupDate);
        setFollowupOutcome(followupOutcome);
    }
}
