/*
 * This file is generated by jOOQ.
 */
package edu.alma.teamleft.tables.records;


import edu.alma.teamleft.tables.PhoneNumber;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhoneNumberRecord extends TableRecordImpl<PhoneNumberRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.phone_number.phone_number_id</code>.
     */
    public void setPhoneNumberId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.phone_number.phone_number_id</code>.
     */
    public Integer getPhoneNumberId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.phone_number.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.phone_number.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.phone_number.number_type_id</code>.
     */
    public void setNumberTypeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.phone_number.number_type_id</code>.
     */
    public Integer getNumberTypeId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PhoneNumber.PHONE_NUMBER.PHONE_NUMBER_ID;
    }

    @Override
    public Field<String> field2() {
        return PhoneNumber.PHONE_NUMBER.PHONE_NUMBER_;
    }

    @Override
    public Field<Integer> field3() {
        return PhoneNumber.PHONE_NUMBER.NUMBER_TYPE_ID;
    }

    @Override
    public Integer component1() {
        return getPhoneNumberId();
    }

    @Override
    public String component2() {
        return getPhoneNumber();
    }

    @Override
    public Integer component3() {
        return getNumberTypeId();
    }

    @Override
    public Integer value1() {
        return getPhoneNumberId();
    }

    @Override
    public String value2() {
        return getPhoneNumber();
    }

    @Override
    public Integer value3() {
        return getNumberTypeId();
    }

    @Override
    public PhoneNumberRecord value1(Integer value) {
        setPhoneNumberId(value);
        return this;
    }

    @Override
    public PhoneNumberRecord value2(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public PhoneNumberRecord value3(Integer value) {
        setNumberTypeId(value);
        return this;
    }

    @Override
    public PhoneNumberRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhoneNumberRecord
     */
    public PhoneNumberRecord() {
        super(PhoneNumber.PHONE_NUMBER);
    }

    /**
     * Create a detached, initialised PhoneNumberRecord
     */
    public PhoneNumberRecord(Integer phoneNumberId, String phoneNumber, Integer numberTypeId) {
        super(PhoneNumber.PHONE_NUMBER);

        setPhoneNumberId(phoneNumberId);
        setPhoneNumber(phoneNumber);
        setNumberTypeId(numberTypeId);
    }
}
