/*
 * This file is generated by jOOQ.
 */
package edu.alma.teamleft.tables.records;


import edu.alma.teamleft.tables.PhoneNumberType;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhoneNumberTypeRecord extends TableRecordImpl<PhoneNumberTypeRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.phone_number_type.number_type_id</code>.
     */
    public void setNumberTypeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.phone_number_type.number_type_id</code>.
     */
    public Integer getNumberTypeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.phone_number_type.number_type</code>.
     */
    public void setNumberType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.phone_number_type.number_type</code>.
     */
    public String getNumberType() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PhoneNumberType.PHONE_NUMBER_TYPE.NUMBER_TYPE_ID;
    }

    @Override
    public Field<String> field2() {
        return PhoneNumberType.PHONE_NUMBER_TYPE.NUMBER_TYPE;
    }

    @Override
    public Integer component1() {
        return getNumberTypeId();
    }

    @Override
    public String component2() {
        return getNumberType();
    }

    @Override
    public Integer value1() {
        return getNumberTypeId();
    }

    @Override
    public String value2() {
        return getNumberType();
    }

    @Override
    public PhoneNumberTypeRecord value1(Integer value) {
        setNumberTypeId(value);
        return this;
    }

    @Override
    public PhoneNumberTypeRecord value2(String value) {
        setNumberType(value);
        return this;
    }

    @Override
    public PhoneNumberTypeRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhoneNumberTypeRecord
     */
    public PhoneNumberTypeRecord() {
        super(PhoneNumberType.PHONE_NUMBER_TYPE);
    }

    /**
     * Create a detached, initialised PhoneNumberTypeRecord
     */
    public PhoneNumberTypeRecord(Integer numberTypeId, String numberType) {
        super(PhoneNumberType.PHONE_NUMBER_TYPE);

        setNumberTypeId(numberTypeId);
        setNumberType(numberType);
    }
}
