/*
 * This file is generated by jOOQ.
 */
package edu.alma.teamleft.tables.records;


import edu.alma.teamleft.tables.Status;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusRecord extends TableRecordImpl<StatusRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.status.status_id</code>.
     */
    public void setStatusId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.status.status_id</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.status.status_name</code>.
     */
    public void setStatusName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.status.status_name</code>.
     */
    public String getStatusName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Status.STATUS.STATUS_ID;
    }

    @Override
    public Field<String> field2() {
        return Status.STATUS.STATUS_NAME;
    }

    @Override
    public Integer component1() {
        return getStatusId();
    }

    @Override
    public String component2() {
        return getStatusName();
    }

    @Override
    public Integer value1() {
        return getStatusId();
    }

    @Override
    public String value2() {
        return getStatusName();
    }

    @Override
    public StatusRecord value1(Integer value) {
        setStatusId(value);
        return this;
    }

    @Override
    public StatusRecord value2(String value) {
        setStatusName(value);
        return this;
    }

    @Override
    public StatusRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatusRecord
     */
    public StatusRecord() {
        super(Status.STATUS);
    }

    /**
     * Create a detached, initialised StatusRecord
     */
    public StatusRecord(Integer statusId, String statusName) {
        super(Status.STATUS);

        setStatusId(statusId);
        setStatusName(statusName);
    }
}
