/*
 * This file is generated by jOOQ.
 */
package edu.alma.teamleft.tables.records;


import edu.alma.teamleft.tables.Ticket;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketRecord extends TableRecordImpl<TicketRecord> implements Record10<Integer, String, String, Integer, Integer, LocalDateTime, LocalDateTime, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ticket.ticket_id</code>.
     */
    public void setTicketId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ticket.ticket_id</code>.
     */
    public Integer getTicketId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ticket.subject</code>.
     */
    public void setSubject(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ticket.subject</code>.
     */
    public String getSubject() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ticket.details</code>.
     */
    public void setDetails(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ticket.details</code>.
     */
    public String getDetails() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ticket.client_id</code>.
     */
    public void setClientId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ticket.client_id</code>.
     */
    public Integer getClientId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.ticket.creator_of_ticket</code>.
     */
    public void setCreatorOfTicket(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ticket.creator_of_ticket</code>.
     */
    public Integer getCreatorOfTicket() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.ticket.entry_date</code>.
     */
    public void setEntryDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ticket.entry_date</code>.
     */
    public LocalDateTime getEntryDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.ticket.call_date</code>.
     */
    public void setCallDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ticket.call_date</code>.
     */
    public LocalDateTime getCallDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.ticket.status_id</code>.
     */
    public void setStatusId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.ticket.status_id</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.ticket.service_type_id</code>.
     */
    public void setServiceTypeId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.ticket.service_type_id</code>.
     */
    public Integer getServiceTypeId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.ticket.notes</code>.
     */
    public void setNotes(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.ticket.notes</code>.
     */
    public String getNotes() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, Integer, Integer, LocalDateTime, LocalDateTime, Integer, Integer, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, Integer, Integer, LocalDateTime, LocalDateTime, Integer, Integer, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Ticket.TICKET.TICKET_ID;
    }

    @Override
    public Field<String> field2() {
        return Ticket.TICKET.SUBJECT;
    }

    @Override
    public Field<String> field3() {
        return Ticket.TICKET.DETAILS;
    }

    @Override
    public Field<Integer> field4() {
        return Ticket.TICKET.CLIENT_ID;
    }

    @Override
    public Field<Integer> field5() {
        return Ticket.TICKET.CREATOR_OF_TICKET;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Ticket.TICKET.ENTRY_DATE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Ticket.TICKET.CALL_DATE;
    }

    @Override
    public Field<Integer> field8() {
        return Ticket.TICKET.STATUS_ID;
    }

    @Override
    public Field<Integer> field9() {
        return Ticket.TICKET.SERVICE_TYPE_ID;
    }

    @Override
    public Field<String> field10() {
        return Ticket.TICKET.NOTES;
    }

    @Override
    public Integer component1() {
        return getTicketId();
    }

    @Override
    public String component2() {
        return getSubject();
    }

    @Override
    public String component3() {
        return getDetails();
    }

    @Override
    public Integer component4() {
        return getClientId();
    }

    @Override
    public Integer component5() {
        return getCreatorOfTicket();
    }

    @Override
    public LocalDateTime component6() {
        return getEntryDate();
    }

    @Override
    public LocalDateTime component7() {
        return getCallDate();
    }

    @Override
    public Integer component8() {
        return getStatusId();
    }

    @Override
    public Integer component9() {
        return getServiceTypeId();
    }

    @Override
    public String component10() {
        return getNotes();
    }

    @Override
    public Integer value1() {
        return getTicketId();
    }

    @Override
    public String value2() {
        return getSubject();
    }

    @Override
    public String value3() {
        return getDetails();
    }

    @Override
    public Integer value4() {
        return getClientId();
    }

    @Override
    public Integer value5() {
        return getCreatorOfTicket();
    }

    @Override
    public LocalDateTime value6() {
        return getEntryDate();
    }

    @Override
    public LocalDateTime value7() {
        return getCallDate();
    }

    @Override
    public Integer value8() {
        return getStatusId();
    }

    @Override
    public Integer value9() {
        return getServiceTypeId();
    }

    @Override
    public String value10() {
        return getNotes();
    }

    @Override
    public TicketRecord value1(Integer value) {
        setTicketId(value);
        return this;
    }

    @Override
    public TicketRecord value2(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public TicketRecord value3(String value) {
        setDetails(value);
        return this;
    }

    @Override
    public TicketRecord value4(Integer value) {
        setClientId(value);
        return this;
    }

    @Override
    public TicketRecord value5(Integer value) {
        setCreatorOfTicket(value);
        return this;
    }

    @Override
    public TicketRecord value6(LocalDateTime value) {
        setEntryDate(value);
        return this;
    }

    @Override
    public TicketRecord value7(LocalDateTime value) {
        setCallDate(value);
        return this;
    }

    @Override
    public TicketRecord value8(Integer value) {
        setStatusId(value);
        return this;
    }

    @Override
    public TicketRecord value9(Integer value) {
        setServiceTypeId(value);
        return this;
    }

    @Override
    public TicketRecord value10(String value) {
        setNotes(value);
        return this;
    }

    @Override
    public TicketRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, LocalDateTime value6, LocalDateTime value7, Integer value8, Integer value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketRecord
     */
    public TicketRecord() {
        super(Ticket.TICKET);
    }

    /**
     * Create a detached, initialised TicketRecord
     */
    public TicketRecord(Integer ticketId, String subject, String details, Integer clientId, Integer creatorOfTicket, LocalDateTime entryDate, LocalDateTime callDate, Integer statusId, Integer serviceTypeId, String notes) {
        super(Ticket.TICKET);

        setTicketId(ticketId);
        setSubject(subject);
        setDetails(details);
        setClientId(clientId);
        setCreatorOfTicket(creatorOfTicket);
        setEntryDate(entryDate);
        setCallDate(callDate);
        setStatusId(statusId);
        setServiceTypeId(serviceTypeId);
        setNotes(notes);
    }
}
